# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20180516_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
