# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20180511_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_follows',
            field=models.ManyToManyField(related_name='follows', to='insta.Profile'),
        ),
    ]
