# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20180511_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='name',
        ),
        migrations.AddField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
