# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20180511_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followed',
        ),
    ]
