# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20180514_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
